from django.urls import path

from kitchen.views import (
    index,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishAddCookView,
    DishRemoveCookView,
    DishUpdateIngredientView,
    DishDeleteView,
    IngredientListView,
    IngredientDetailView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView)

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/",
         DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/<int:pk>/",
         DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dish-types/create/",
         DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/",
         DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/",
         DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dishes/",
         DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/",
         DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/",
         DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/",
         DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/add/",
         DishAddCookView.as_view(), name="dish-add"),
    path("dishes/<int:pk>/remove/",
         DishRemoveCookView.as_view(), name="dish-remove"),
    path("dishes/<int:pk>/update-ingredient/",
         DishUpdateIngredientView.as_view(), name="dish-update-ingredient"),
    path("dishes/<int:pk>/delete/",
         DishDeleteView.as_view(), name="dish-delete"),
    path("ingredients/",
         IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/<int:pk>/",
         IngredientDetailView.as_view(), name="ingredient-detail"),
    path("ingredients/create/",
         IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredients/<int:pk>/update/",
         IngredientUpdateView.as_view(), name="ingredient-update"),
    path("ingredients/<int:pk>/delete/",
         IngredientDeleteView.as_view(), name="ingredient-delete"),
    path("cooks/",
         CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/",
         CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/",
         CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/",
         CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/",
         CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen"
